version: '3.1'

services:

  db:
    image: mariadb
    restart: always
    env_file:
      - .env

  # db2:
  #   image: postgres
  #   restart: always
  #   env_file:
  #     - .env

  # adminer:
  #   image: adminer
  #   restart: always
  #   ports:
  #     - 8080:8080